[project]
name = "week9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cs50>=9.4.0",
    "flask>=3.1.1",
    "flask-session>=0.8.0",
]
