const WORDS = [
    'apple', 'application', 'apply', 'approach', 'approve', 
    'banana', 'band', 'bank', 'bar', 'base', 'basic',
    'cat', 'car', 'card', 'care', 'carry', 'case',
    'dog', 'data', 'date', 'day', 'deal', 'death',
    'elephant', 'email', 'end', 'energy', 'environment', 'error',
    'fish', 'file', 'final', 'find', 'fire', 'first',
    'great', 'green', 'ground', 'group', 'grow', 'growth',
    'house', 'hand', 'happen', 'happy', 'hard', 'have',
    'internet', 'idea', 'image', 'important', 'include', 'increase',
    'javascript', 'job', 'join', 'just', 'jump', 'justice',
    'keep', 'key', 'kind', 'know', 'knowledge', 'kitchen',
    'learn', 'language', 'large', 'last', 'late', 'law',
    'make', 'man', 'manage', 'market', 'may', 'mean',
    'new', 'news', 'next', 'night', 'not', 'note',
    'open', 'option', 'order', 'organization', 'other', 'out',
    'page', 'part', 'particular', 'party', 'pass', 'past',
    'question', 'quite', 'quote', 'quality', 'quick', 'quiet',
    'real', 'really', 'reason', 'receive', 'record', 'red',
    'school', 'science', 'search', 'season', 'second', 'section',
    'table', 'take', 'talk', 'task', 'tax', 'teach',
    'under', 'understand', 'unit', 'until', 'up', 'upon',
    'value', 'various', 'very', 'view', 'voice', 'vote',
    'water', 'way', 'we', 'week', 'well', 'what',
    'year', 'yes', 'yet', 'you', 'young', 'your'
];
